-- ==============================================================================
-- OMNIDOCK - DATOS DE PRUEBA (v4)
-- ORDEN: 00_drop.sql -> 01_ddl.sql -> 02_insert.sql -> 03_verificar.sql
--
-- Ejecutar SIEMPRE sobre tablas recien creadas: los IDs de usuarios, bahias,
-- vehiculos y reservas se numeran solos desde 1, en el orden de este archivo.
-- Todas las fechas van en UTC, igual que el backend.
-- ==============================================================================

-- 1. CATALOGOS (ID explicito: el backend los usa por numero, ver domain/Estados.java)
INSERT INTO ROL (ID_ROL, NOMBRE_ROL) VALUES (1, 'ADMINISTRADOR');
INSERT INTO ROL (ID_ROL, NOMBRE_ROL) VALUES (2, 'USUARIO');
INSERT INTO ROL (ID_ROL, NOMBRE_ROL) VALUES (3, 'COLABORADOR');

INSERT INTO TIPO_VEHICULO (ID_TIPO_VEHICULO, NOMBRE_TIPO) VALUES (1, 'BICICLETA');
INSERT INTO TIPO_VEHICULO (ID_TIPO_VEHICULO, NOMBRE_TIPO) VALUES (2, 'SCOOTER');

INSERT INTO ESTADO_BAHIA (ID_ESTADO, NOMBRE_ESTADO) VALUES (1, 'DISPONIBLE');
INSERT INTO ESTADO_BAHIA (ID_ESTADO, NOMBRE_ESTADO) VALUES (2, 'RESERVADA');
INSERT INTO ESTADO_BAHIA (ID_ESTADO, NOMBRE_ESTADO) VALUES (3, 'OCUPADA');
INSERT INTO ESTADO_BAHIA (ID_ESTADO, NOMBRE_ESTADO) VALUES (4, 'FUERA_DE_SERVICIO');

-- 2. USUARIOS (IDs 1 al 20). Rol: 1 administrador, 2 usuario, 3 colaborador
INSERT INTO USUARIO (RUT, NOMBRE_COMPLETO, EMAIL_INSTITUCIONAL, PASSWORD_PROTOTIPO, ID_ROL) VALUES ('17234567-K', 'Camila Soto',      'csoto@duocuc.cl',     'admin123', 1); --  1
INSERT INTO USUARIO (RUT, NOMBRE_COMPLETO, EMAIL_INSTITUCIONAL, PASSWORD_PROTOTIPO, ID_ROL) VALUES ('16444333-2', 'Joaquin Castillo', 'jcastillo@duocuc.cl', 'admin123', 1); --  2
INSERT INTO USUARIO (RUT, NOMBRE_COMPLETO, EMAIL_INSTITUCIONAL, PASSWORD_PROTOTIPO, ID_ROL) VALUES ('15888999-5', 'Ignacio Castro',   'icastro@duocuc.cl',   'admin123', 1); --  3
INSERT INTO USUARIO (RUT, NOMBRE_COMPLETO, EMAIL_INSTITUCIONAL, PASSWORD_PROTOTIPO, ID_ROL) VALUES ('19876543-2', 'Matias Munoz',     'mmunoz@duocuc.cl',    'user123',  2); --  4
INSERT INTO USUARIO (RUT, NOMBRE_COMPLETO, EMAIL_INSTITUCIONAL, PASSWORD_PROTOTIPO, ID_ROL) VALUES ('20123456-7', 'Sofia Silva',      'ssilva@duocuc.cl',    'user123',  2); --  5
INSERT INTO USUARIO (RUT, NOMBRE_COMPLETO, EMAIL_INSTITUCIONAL, PASSWORD_PROTOTIPO, ID_ROL) VALUES ('21345678-9', 'Lucas Perez',      'lperez@duocuc.cl',    'user123',  2); --  6
INSERT INTO USUARIO (RUT, NOMBRE_COMPLETO, EMAIL_INSTITUCIONAL, PASSWORD_PROTOTIPO, ID_ROL) VALUES ('19999888-3', 'Diego Torres',     'dtorres@duocuc.cl',   'user123',  2); --  7
INSERT INTO USUARIO (RUT, NOMBRE_COMPLETO, EMAIL_INSTITUCIONAL, PASSWORD_PROTOTIPO, ID_ROL) VALUES ('20555444-K', 'Antonia Flores',   'aflores@duocuc.cl',   'user123',  2); --  8
INSERT INTO USUARIO (RUT, NOMBRE_COMPLETO, EMAIL_INSTITUCIONAL, PASSWORD_PROTOTIPO, ID_ROL) VALUES ('21111222-3', 'Isidora Vega',     'ivega@duocuc.cl',     'user123',  2); --  9
INSERT INTO USUARIO (RUT, NOMBRE_COMPLETO, EMAIL_INSTITUCIONAL, PASSWORD_PROTOTIPO, ID_ROL) VALUES ('20888777-1', 'Florencia Gomez',  'fgomez@duocuc.cl',    'user123',  2); -- 10
INSERT INTO USUARIO (RUT, NOMBRE_COMPLETO, EMAIL_INSTITUCIONAL, PASSWORD_PROTOTIPO, ID_ROL) VALUES ('19555666-4', 'Gabriel Fuentes',  'gfuentes@duocuc.cl',  'user123',  2); -- 11
INSERT INTO USUARIO (RUT, NOMBRE_COMPLETO, EMAIL_INSTITUCIONAL, PASSWORD_PROTOTIPO, ID_ROL) VALUES ('21444555-6', 'Fernanda Navarro', 'fnavarro@duocuc.cl',  'user123',  2); -- 12
INSERT INTO USUARIO (RUT, NOMBRE_COMPLETO, EMAIL_INSTITUCIONAL, PASSWORD_PROTOTIPO, ID_ROL) VALUES ('20333222-8', 'Benjamin Herrera', 'bherrera@duocuc.cl',  'user123',  2); -- 13
INSERT INTO USUARIO (RUT, NOMBRE_COMPLETO, EMAIL_INSTITUCIONAL, PASSWORD_PROTOTIPO, ID_ROL) VALUES ('19111333-0', 'Pia Vargas',       'pvargas@duocuc.cl',   'user123',  2); -- 14
INSERT INTO USUARIO (RUT, NOMBRE_COMPLETO, EMAIL_INSTITUCIONAL, PASSWORD_PROTOTIPO, ID_ROL) VALUES ('20777666-5', 'Amanda Ruiz',      'aruiz@duocuc.cl',     'user123',  2); -- 15
INSERT INTO USUARIO (RUT, NOMBRE_COMPLETO, EMAIL_INSTITUCIONAL, PASSWORD_PROTOTIPO, ID_ROL) VALUES ('18765432-1', 'Valentina Reyes',  'vreyes@duocuc.cl',    'colab123', 3); -- 16
INSERT INTO USUARIO (RUT, NOMBRE_COMPLETO, EMAIL_INSTITUCIONAL, PASSWORD_PROTOTIPO, ID_ROL) VALUES ('18222333-4', 'Tomas Rojas',      'trojas@duocuc.cl',    'colab123', 3); -- 17
INSERT INTO USUARIO (RUT, NOMBRE_COMPLETO, EMAIL_INSTITUCIONAL, PASSWORD_PROTOTIPO, ID_ROL) VALUES ('17999111-5', 'Martin Diaz',      'mdiaz@duocuc.cl',     'colab123', 3); -- 18
INSERT INTO USUARIO (RUT, NOMBRE_COMPLETO, EMAIL_INSTITUCIONAL, PASSWORD_PROTOTIPO, ID_ROL) VALUES ('18333444-6', 'Catalina Morales', 'cmorales@duocuc.cl',  'colab123', 3); -- 19
INSERT INTO USUARIO (RUT, NOMBRE_COMPLETO, EMAIL_INSTITUCIONAL, PASSWORD_PROTOTIPO, ID_ROL) VALUES ('17111999-8', 'Vicente Romero',   'vromero@duocuc.cl',   'colab123', 3); -- 20

-- 3. BAHIAS (IDs 1 al 4). Estado: 1 disponible, 2 reservada, 3 ocupada, 4 fuera de servicio
--    El estado de cada bahia se explica con los datos de mas abajo:
INSERT INTO BAHIA (CODIGO_IOT, UBICACION, ID_ESTADO, ID_TIPO_PERMITIDO) VALUES ('RACK-BICI-01',  'Sede Maipu - Acceso Norte',  1, 1); -- 1: libre
INSERT INTO BAHIA (CODIGO_IOT, UBICACION, ID_ESTADO, ID_TIPO_PERMITIDO) VALUES ('RACK-BICI-02',  'Sede Maipu - Acceso Norte',  4, 1); -- 2: ticket abierto (seccion 8)
INSERT INTO BAHIA (CODIGO_IOT, UBICACION, ID_ESTADO, ID_TIPO_PERMITIDO) VALUES ('RACK-SCOOT-01', 'Sede Maipu - Patio Central', 3, 2); -- 3: uso activo (seccion 7)
INSERT INTO BAHIA (CODIGO_IOT, UBICACION, ID_ESTADO, ID_TIPO_PERMITIDO) VALUES ('RACK-SCOOT-02', 'Sede Maipu - Patio Central', 2, 2); -- 4: reserva pendiente (seccion 6)

-- 4. DISPOSITIVOS IoT (uno por bahia, IDs 1 al 4)
INSERT INTO DISPOSITIVO_IOT (ID_BAHIA, DIRECCION_MAC, FIRMWARE_VERSION, ESTADO_CONEXION, ULTIMO_PING) VALUES (1, '00:1B:44:11:3A:B7', 'v1.0.5', 'ONLINE',  SYS_EXTRACT_UTC(SYSTIMESTAMP) - INTERVAL '1' MINUTE);
INSERT INTO DISPOSITIVO_IOT (ID_BAHIA, DIRECCION_MAC, FIRMWARE_VERSION, ESTADO_CONEXION, ULTIMO_PING) VALUES (2, '00:1B:44:11:3A:B8', 'v1.0.5', 'OFFLINE', SYS_EXTRACT_UTC(SYSTIMESTAMP) - INTERVAL '2' HOUR);
INSERT INTO DISPOSITIVO_IOT (ID_BAHIA, DIRECCION_MAC, FIRMWARE_VERSION, ESTADO_CONEXION, ULTIMO_PING) VALUES (3, '00:1B:44:11:3A:B9', 'v1.0.5', 'ONLINE',  SYS_EXTRACT_UTC(SYSTIMESTAMP) - INTERVAL '1' MINUTE);
INSERT INTO DISPOSITIVO_IOT (ID_BAHIA, DIRECCION_MAC, FIRMWARE_VERSION, ESTADO_CONEXION, ULTIMO_PING) VALUES (4, '00:1B:44:11:3A:C0', 'v1.0.5', 'ONLINE',  SYS_EXTRACT_UTC(SYSTIMESTAMP) - INTERVAL '1' MINUTE);

-- 5. VEHICULOS (IDs 1 al 10). Tipo: 1 bicicleta, 2 scooter
INSERT INTO VEHICULO (ID_USUARIO, ID_TIPO_VEHICULO, IDENTIFICADOR, ESTADO_VEHICULO) VALUES (4,  1, 'Trek Marlin 5',          'ACTIVO');   --  1
INSERT INTO VEHICULO (ID_USUARIO, ID_TIPO_VEHICULO, IDENTIFICADOR, ESTADO_VEHICULO) VALUES (5,  1, 'Specialized Rockhopper', 'ACTIVO');   --  2
INSERT INTO VEHICULO (ID_USUARIO, ID_TIPO_VEHICULO, IDENTIFICADOR, ESTADO_VEHICULO) VALUES (6,  1, 'Giant Talon',            'ACTIVO');   --  3
INSERT INTO VEHICULO (ID_USUARIO, ID_TIPO_VEHICULO, IDENTIFICADOR, ESTADO_VEHICULO) VALUES (7,  1, 'Oxford Kamikaze',        'ACTIVO');   --  4
INSERT INTO VEHICULO (ID_USUARIO, ID_TIPO_VEHICULO, IDENTIFICADOR, ESTADO_VEHICULO) VALUES (8,  1, 'Bianchi Aggressor',      'INACTIVO'); --  5 (borrado logico)
INSERT INTO VEHICULO (ID_USUARIO, ID_TIPO_VEHICULO, IDENTIFICADOR, ESTADO_VEHICULO) VALUES (9,  2, 'Xiaomi Mi Pro 2',        'ACTIVO');   --  6
INSERT INTO VEHICULO (ID_USUARIO, ID_TIPO_VEHICULO, IDENTIFICADOR, ESTADO_VEHICULO) VALUES (10, 2, 'Segway Ninebot',         'ACTIVO');   --  7
INSERT INTO VEHICULO (ID_USUARIO, ID_TIPO_VEHICULO, IDENTIFICADOR, ESTADO_VEHICULO) VALUES (11, 2, 'Dualtron Mini',          'ACTIVO');   --  8
INSERT INTO VEHICULO (ID_USUARIO, ID_TIPO_VEHICULO, IDENTIFICADOR, ESTADO_VEHICULO) VALUES (12, 2, 'Zero 9',                 'ACTIVO');   --  9
INSERT INTO VEHICULO (ID_USUARIO, ID_TIPO_VEHICULO, IDENTIFICADOR, ESTADO_VEHICULO) VALUES (13, 2, 'Niu KQi3',               'ACTIVO');   -- 10

-- 6. RESERVAS (IDs 1 al 6). La expiracion es la solicitud + 15 minutos (ventana de reserva)
-- Historicas (21 y 22 de septiembre; en hora de Chile fueron a las 07:30, 08:00, 09:00 y 10:30)
INSERT INTO RESERVA (ID_USUARIO, ID_BAHIA, ID_VEHICULO, FECHA_SOLICITUD, FECHA_EXPIRACION, ESTADO_RESERVA) VALUES (4, 1, 1, TIMESTAMP '2026-09-21 10:30:00', TIMESTAMP '2026-09-21 10:45:00', 'CONCRETADA'); -- 1
INSERT INTO RESERVA (ID_USUARIO, ID_BAHIA, ID_VEHICULO, FECHA_SOLICITUD, FECHA_EXPIRACION, ESTADO_RESERVA) VALUES (5, 2, 2, TIMESTAMP '2026-09-21 11:00:00', TIMESTAMP '2026-09-21 11:15:00', 'CONCRETADA'); -- 2
INSERT INTO RESERVA (ID_USUARIO, ID_BAHIA, ID_VEHICULO, FECHA_SOLICITUD, FECHA_EXPIRACION, ESTADO_RESERVA) VALUES (6, 1, 3, TIMESTAMP '2026-09-22 12:00:00', TIMESTAMP '2026-09-22 12:15:00', 'EXPIRADA');   -- 3
INSERT INTO RESERVA (ID_USUARIO, ID_BAHIA, ID_VEHICULO, FECHA_SOLICITUD, FECHA_EXPIRACION, ESTADO_RESERVA) VALUES (9, 3, 6, TIMESTAMP '2026-09-22 13:30:00', TIMESTAMP '2026-09-22 13:45:00', 'CONCRETADA'); -- 4
-- Reserva 5: el usuario 10 ya hizo check-in en la bahia 3 (por eso esta OCUPADA)
INSERT INTO RESERVA (ID_USUARIO, ID_BAHIA, ID_VEHICULO, FECHA_SOLICITUD, FECHA_EXPIRACION, ESTADO_RESERVA) VALUES (10, 3, 7, SYS_EXTRACT_UTC(SYSTIMESTAMP) - INTERVAL '20' MINUTE, SYS_EXTRACT_UTC(SYSTIMESTAMP) - INTERVAL '5' MINUTE, 'CONCRETADA');
-- Reserva 6: el usuario 11 acaba de reservar la bahia 4 (por eso esta RESERVADA).
-- Si nadie hace check-in, el backend la pasa a EXPIRADA a los 15 minutos y libera la bahia.
INSERT INTO RESERVA (ID_USUARIO, ID_BAHIA, ID_VEHICULO, FECHA_SOLICITUD, FECHA_EXPIRACION, ESTADO_RESERVA) VALUES (11, 4, 8, SYS_EXTRACT_UTC(SYSTIMESTAMP), SYS_EXTRACT_UTC(SYSTIMESTAMP) + INTERVAL '15' MINUTE, 'PENDIENTE');

-- 7. USOS (IDs 1 al 4). La reserva 3 expiro, por eso no tiene uso
INSERT INTO TRANSACCION_USO (ID_RESERVA, ID_USUARIO, ID_BAHIA, ID_VEHICULO, FECHA_INICIO, FECHA_FIN, ESTADO_TRANSACCION) VALUES (1, 4, 1, 1, TIMESTAMP '2026-09-21 10:40:00', TIMESTAMP '2026-09-21 15:30:00', 'FINALIZADA');
INSERT INTO TRANSACCION_USO (ID_RESERVA, ID_USUARIO, ID_BAHIA, ID_VEHICULO, FECHA_INICIO, FECHA_FIN, ESTADO_TRANSACCION) VALUES (2, 5, 2, 2, TIMESTAMP '2026-09-21 11:10:00', TIMESTAMP '2026-09-21 21:00:00', 'FINALIZADA');
INSERT INTO TRANSACCION_USO (ID_RESERVA, ID_USUARIO, ID_BAHIA, ID_VEHICULO, FECHA_INICIO, FECHA_FIN, ESTADO_TRANSACCION) VALUES (4, 9, 3, 6, TIMESTAMP '2026-09-22 13:40:00', TIMESTAMP '2026-09-22 20:30:00', 'FINALIZADA');
-- Uso activo: el usuario 10 ocupa la bahia 3 desde hace 10 minutos
INSERT INTO TRANSACCION_USO (ID_RESERVA, ID_USUARIO, ID_BAHIA, ID_VEHICULO, FECHA_INICIO, FECHA_FIN, ESTADO_TRANSACCION) VALUES (5, 10, 3, 7, SYS_EXTRACT_UTC(SYSTIMESTAMP) - INTERVAL '10' MINUTE, NULL, 'ACTIVA');

-- 8. TICKETS DE MANTENCION
-- Ticket 1: ABIERTO sobre la bahia 2 (por eso esta FUERA_DE_SERVICIO), reportado por la colaboradora 16
INSERT INTO TICKET_MANTENIMIENTO (ID_BAHIA, REPORTADO_POR, DESCRIPCION_FALLA, FECHA_REPORTE, FECHA_RESOLUCION, ESTADO_TICKET) VALUES (2, 16, 'Candado trabado: el cerrojo no libera la bicicleta', SYS_EXTRACT_UTC(SYSTIMESTAMP) - INTERVAL '2' HOUR, NULL, 'ABIERTO');
-- Ticket 2: historico RESUELTO sobre la bahia 1 (sirve para medir tiempos de resolucion en Power BI)
INSERT INTO TICKET_MANTENIMIENTO (ID_BAHIA, REPORTADO_POR, DESCRIPCION_FALLA, FECHA_REPORTE, FECHA_RESOLUCION, ESTADO_TICKET) VALUES (1, 17, 'Sensor de ocupacion con lecturas erraticas', TIMESTAMP '2026-09-18 13:00:00', TIMESTAMP '2026-09-19 18:30:00', 'RESUELTO');

-- 9. EVENTOS IoT (un evento por dispositivo)
INSERT INTO LOG_EVENTO_IOT (ID_DISPOSITIVO, TIPO_EVENTO, PAYLOAD_RECIBIDO, FECHA_EVENTO) VALUES (1, 'LECTURA_SENSOR', '{"candadoCerrado": true, "bateria": 85, "estadoConexion": "ONLINE"}', SYS_EXTRACT_UTC(SYSTIMESTAMP) - INTERVAL '1' MINUTE);
INSERT INTO LOG_EVENTO_IOT (ID_DISPOSITIVO, TIPO_EVENTO, PAYLOAD_RECIBIDO, FECHA_EVENTO) VALUES (2, 'ALERTA_FALLA',   '{"candadoCerrado": false, "bateria": 9, "estadoConexion": "OFFLINE", "falla": true}', SYS_EXTRACT_UTC(SYSTIMESTAMP) - INTERVAL '2' HOUR);
INSERT INTO LOG_EVENTO_IOT (ID_DISPOSITIVO, TIPO_EVENTO, PAYLOAD_RECIBIDO, FECHA_EVENTO) VALUES (3, 'LECTURA_SENSOR', '{"candadoCerrado": false, "bateria": 72, "estadoConexion": "ONLINE"}', SYS_EXTRACT_UTC(SYSTIMESTAMP) - INTERVAL '1' MINUTE);
INSERT INTO LOG_EVENTO_IOT (ID_DISPOSITIVO, TIPO_EVENTO, PAYLOAD_RECIBIDO, FECHA_EVENTO) VALUES (4, 'LECTURA_SENSOR', '{"candadoCerrado": true, "bateria": 64, "estadoConexion": "ONLINE"}', SYS_EXTRACT_UTC(SYSTIMESTAMP) - INTERVAL '1' MINUTE);

COMMIT;
