-- ==============================================================================
-- OMNIDOCK - VERIFICACION DE LA BASE (solo consultas, no modifica nada)
-- ==============================================================================

-- 1. CATALOGOS. Debe mostrar exactamente:
--    1 DISPONIBLE, 2 RESERVADA, 3 OCUPADA, 4 FUERA_DE_SERVICIO
SELECT ID_ESTADO, NOMBRE_ESTADO FROM ESTADO_BAHIA ORDER BY ID_ESTADO;
--    1 ADMINISTRADOR, 2 USUARIO, 3 COLABORADOR
SELECT ID_ROL, NOMBRE_ROL FROM ROL ORDER BY ID_ROL;
--    1 BICICLETA, 2 SCOOTER
SELECT ID_TIPO_VEHICULO, NOMBRE_TIPO FROM TIPO_VEHICULO ORDER BY ID_TIPO_VEHICULO;

-- 2. CANTIDAD DE FILAS. Recien cargada debe mostrar: 20, 10, 4, 4, 6, 4, 2, 4
SELECT 'USUARIO' AS TABLA, COUNT(*) AS FILAS FROM USUARIO
UNION ALL SELECT 'VEHICULO', COUNT(*) FROM VEHICULO
UNION ALL SELECT 'BAHIA', COUNT(*) FROM BAHIA
UNION ALL SELECT 'DISPOSITIVO_IOT', COUNT(*) FROM DISPOSITIVO_IOT
UNION ALL SELECT 'RESERVA', COUNT(*) FROM RESERVA
UNION ALL SELECT 'TRANSACCION_USO', COUNT(*) FROM TRANSACCION_USO
UNION ALL SELECT 'TICKET_MANTENIMIENTO', COUNT(*) FROM TICKET_MANTENIMIENTO
UNION ALL SELECT 'LOG_EVENTO_IOT', COUNT(*) FROM LOG_EVENTO_IOT;

-- 3. BAHIAS Y LO QUE EXPLICA SU ESTADO. Para que los datos sean coherentes:
--    RESERVADA  -> RESERVAS_PENDIENTES = 1
--    OCUPADA    -> USOS_ACTIVOS = 1
--    DISPONIBLE -> las tres columnas en 0
--    FUERA_DE_SERVICIO -> normalmente TICKETS_ABIERTOS = 1
SELECT b.ID_BAHIA,
       b.CODIGO_IOT,
       e.NOMBRE_ESTADO,
       (SELECT COUNT(*) FROM RESERVA r WHERE r.ID_BAHIA = b.ID_BAHIA AND r.ESTADO_RESERVA = 'PENDIENTE') AS RESERVAS_PENDIENTES,
       (SELECT COUNT(*) FROM TRANSACCION_USO t WHERE t.ID_BAHIA = b.ID_BAHIA AND t.ESTADO_TRANSACCION = 'ACTIVA') AS USOS_ACTIVOS,
       (SELECT COUNT(*) FROM TICKET_MANTENIMIENTO k WHERE k.ID_BAHIA = b.ID_BAHIA AND k.ESTADO_TICKET IN ('ABIERTO', 'EN_REVISION')) AS TICKETS_ABIERTOS
  FROM BAHIA b
  JOIN ESTADO_BAHIA e ON e.ID_ESTADO = b.ID_ESTADO
 ORDER BY b.ID_BAHIA;

-- 4. VEHICULOS REPETIDOS. No debe devolver filas (si devuelve, los datos se cargaron dos veces)
SELECT ID_USUARIO, IDENTIFICADOR, COUNT(*) AS VECES
  FROM VEHICULO
 GROUP BY ID_USUARIO, IDENTIFICADOR
HAVING COUNT(*) > 1;

-- 5. RESTRICCIONES CHECK. Debe mostrar 6 filas, todas con STATUS = ENABLED:
--    RESERVA CHK_ESTADO_RESERVA, TICKET_MANTENIMIENTO CHK_ESTADO_TICKET,
--    TRANSACCION_USO CHK_ESTADO_TRANSACCION y CHK_FECHAS,
--    USUARIO CHK_ESTADO_USUARIO, VEHICULO CHK_ESTADO_VEHICULO
SELECT TABLE_NAME, CONSTRAINT_NAME, STATUS
  FROM USER_CONSTRAINTS
 WHERE CONSTRAINT_TYPE = 'C'
   AND CONSTRAINT_NAME LIKE 'CHK%'
 ORDER BY TABLE_NAME, CONSTRAINT_NAME;
