-- ==============================================================================
-- OMNIDOCK - CAPA ANALITICA PARA POWER BI
-- AUTOR: Crisler Romero (Arquitectura de Datos y BI)
-- Modelo en estrella hecho con vistas sobre las tablas transaccionales:
--   4 dimensiones: V_DIM_FECHA, V_DIM_BAHIA, V_DIM_USUARIO, V_DIM_VEHICULO
--   4 hechos:      V_HECHO_USO, V_HECHO_RESERVA, V_HECHO_TICKET, V_HECHO_EVENTO_IOT
-- ==============================================================================


-- DIMENSIONES

-- Calendario: un dia por fila, del 01/06/2026 al 31/12/2027
CREATE OR REPLACE VIEW V_DIM_FECHA AS
SELECT d.FECHA,
       EXTRACT(YEAR FROM d.FECHA) AS ANIO,
       EXTRACT(MONTH FROM d.FECHA) AS MES,
       TO_CHAR(d.FECHA, 'fmMonth', 'NLS_DATE_LANGUAGE=SPANISH') AS NOMBRE_MES,
       TO_CHAR(d.FECHA, 'YYYY-MM') AS ANIO_MES,
       EXTRACT(DAY FROM d.FECHA) AS DIA,
       1 + d.FECHA - TRUNC(d.FECHA, 'IW') AS DIA_SEMANA,   -- 1 lunes ... 7 domingo
       TO_CHAR(d.FECHA, 'fmDay', 'NLS_DATE_LANGUAGE=SPANISH') AS NOMBRE_DIA,
       CASE WHEN 1 + d.FECHA - TRUNC(d.FECHA, 'IW') >= 6 THEN 'SI' ELSE 'NO' END AS FIN_DE_SEMANA
  FROM (SELECT DATE '2026-06-01' + LEVEL - 1 AS FECHA
          FROM DUAL
       CONNECT BY LEVEL <= 579) d;

-- Bahia
CREATE OR REPLACE VIEW V_DIM_BAHIA AS
SELECT b.ID_BAHIA,
       b.CODIGO_IOT,
       b.UBICACION,
       tv.NOMBRE_TIPO AS TIPO_PERMITIDO,
       e.NOMBRE_ESTADO AS ESTADO_ACTUAL,
       d.ESTADO_CONEXION,
       d.FIRMWARE_VERSION
  FROM BAHIA b
  JOIN TIPO_VEHICULO tv ON tv.ID_TIPO_VEHICULO = b.ID_TIPO_PERMITIDO
  JOIN ESTADO_BAHIA e ON e.ID_ESTADO = b.ID_ESTADO
  LEFT JOIN DISPOSITIVO_IOT d ON d.ID_BAHIA = b.ID_BAHIA;

-- Usuario
CREATE OR REPLACE VIEW V_DIM_USUARIO AS
SELECT u.ID_USUARIO,
       r.NOMBRE_ROL AS ROL,
       u.ESTADO_SINCRONIZACION AS ESTADO_USUARIO
  FROM USUARIO u
  JOIN ROL r ON r.ID_ROL = u.ID_ROL;

-- Vehiculo
CREATE OR REPLACE VIEW V_DIM_VEHICULO AS
SELECT v.ID_VEHICULO,
       v.ID_USUARIO,
       tv.NOMBRE_TIPO AS TIPO_VEHICULO,
       v.ESTADO_VEHICULO
  FROM VEHICULO v
  JOIN TIPO_VEHICULO tv ON tv.ID_TIPO_VEHICULO = v.ID_TIPO_VEHICULO;


-- FACT

-- Uso de bahias
CREATE OR REPLACE VIEW V_HECHO_USO AS
SELECT x.ID_TRANSACCION,
       x.ID_RESERVA,
       x.ID_USUARIO,
       x.ID_BAHIA,
       x.ID_VEHICULO,
       TRUNC(x.INICIO_LOCAL) AS FECHA,
       TO_NUMBER(TO_CHAR(x.INICIO_LOCAL, 'HH24')) AS HORA_INICIO,
       x.INICIO_LOCAL,
       x.FIN_LOCAL,
       x.ESTADO_TRANSACCION,
       ROUND((CAST(x.FECHA_FIN AS DATE) - CAST(x.FECHA_INICIO AS DATE)) * 1440) AS MINUTOS_USO
  FROM (SELECT t.ID_TRANSACCION,
               t.ID_RESERVA,
               t.ID_USUARIO,
               t.ID_BAHIA,
               t.ID_VEHICULO,
               t.ESTADO_TRANSACCION,
               t.FECHA_INICIO,
               t.FECHA_FIN,
               CAST(FROM_TZ(t.FECHA_INICIO, 'UTC') AT TIME ZONE 'America/Santiago' AS DATE) AS INICIO_LOCAL,
               CAST(FROM_TZ(t.FECHA_FIN, 'UTC') AT TIME ZONE 'America/Santiago' AS DATE) AS FIN_LOCAL
          FROM TRANSACCION_USO t) x;

-- Reservas
-- MINUTOS_VENTANA es el plazo que tenia para llegar; MINUTOS_HASTA_CHECKIN es lo que tardo
CREATE OR REPLACE VIEW V_HECHO_RESERVA AS
SELECT x.ID_RESERVA,
       x.ID_USUARIO,
       x.ID_BAHIA,
       x.ID_VEHICULO,
       TRUNC(x.SOLICITUD_LOCAL) AS FECHA,
       TO_NUMBER(TO_CHAR(x.SOLICITUD_LOCAL, 'HH24')) AS HORA_SOLICITUD,
       x.SOLICITUD_LOCAL,
       x.ESTADO_RESERVA,
       ROUND((CAST(x.FECHA_EXPIRACION AS DATE) - CAST(x.FECHA_SOLICITUD AS DATE)) * 1440) AS MINUTOS_VENTANA,
       ROUND((CAST(x.FECHA_CHECKIN AS DATE) - CAST(x.FECHA_SOLICITUD AS DATE)) * 1440) AS MINUTOS_HASTA_CHECKIN
  FROM (SELECT r.ID_RESERVA,
               r.ID_USUARIO,
               r.ID_BAHIA,
               r.ID_VEHICULO,
               r.ESTADO_RESERVA,
               r.FECHA_SOLICITUD,
               r.FECHA_EXPIRACION,
               CAST(FROM_TZ(r.FECHA_SOLICITUD, 'UTC') AT TIME ZONE 'America/Santiago' AS DATE) AS SOLICITUD_LOCAL,
               (SELECT MIN(t.FECHA_INICIO)
                  FROM TRANSACCION_USO t
                 WHERE t.ID_RESERVA = r.ID_RESERVA) AS FECHA_CHECKIN
          FROM RESERVA r) x;

-- Tickets de mantencion
CREATE OR REPLACE VIEW V_HECHO_TICKET AS
SELECT x.ID_TICKET,
       x.ID_BAHIA,
       x.ID_USUARIO,
       TRUNC(x.REPORTE_LOCAL) AS FECHA,
       x.REPORTE_LOCAL,
       x.ESTADO_TICKET,
       ROUND((CAST(x.FECHA_RESOLUCION AS DATE) - CAST(x.FECHA_REPORTE AS DATE)) * 24, 1) AS HORAS_RESOLUCION
  FROM (SELECT k.ID_TICKET,
               k.ID_BAHIA,
               k.REPORTADO_POR AS ID_USUARIO,
               k.ESTADO_TICKET,
               k.FECHA_REPORTE,
               k.FECHA_RESOLUCION,
               CAST(FROM_TZ(k.FECHA_REPORTE, 'UTC') AT TIME ZONE 'America/Santiago' AS DATE) AS REPORTE_LOCAL
          FROM TICKET_MANTENIMIENTO k) x;

-- Eventos IoT
CREATE OR REPLACE VIEW V_HECHO_EVENTO_IOT AS
SELECT x.ID_LOG,
       x.ID_DISPOSITIVO,
       x.ID_BAHIA,
       TRUNC(x.EVENTO_LOCAL) AS FECHA,
       TO_NUMBER(TO_CHAR(x.EVENTO_LOCAL, 'HH24')) AS HORA_EVENTO,
       x.EVENTO_LOCAL,
       x.TIPO_EVENTO,
       x.BATERIA
  FROM (SELECT l.ID_LOG,
               l.ID_DISPOSITIVO,
               d.ID_BAHIA,
               l.TIPO_EVENTO,
               CAST(FROM_TZ(l.FECHA_EVENTO, 'UTC') AT TIME ZONE 'America/Santiago' AS DATE) AS EVENTO_LOCAL,
               JSON_VALUE(l.PAYLOAD_RECIBIDO, '$.bateria' RETURNING NUMBER NULL ON ERROR) AS BATERIA
          FROM LOG_EVENTO_IOT l
          JOIN DISPOSITIVO_IOT d ON d.ID_DISPOSITIVO = l.ID_DISPOSITIVO) x;
