-- ==============================================================================
-- OMNIDOCK - CONSULTAS ANALITICAS
-- ==============================================================================

-- 0. LAS VISTAS EXISTEN. Debe mostrar 8 filas, todas con STATUS = VALID
SELECT OBJECT_NAME, STATUS
  FROM USER_OBJECTS
 WHERE OBJECT_TYPE = 'VIEW'
   AND (OBJECT_NAME LIKE 'V_DIM%' OR OBJECT_NAME LIKE 'V_HECHO%')
 ORDER BY OBJECT_NAME;

-- 1. OCUPACION ACTUAL POR UBICACION
--    Cuantas bahias hay en cada estado y que porcentaje esta en uso (reservada u ocupada)
SELECT UBICACION,
       COUNT(*) AS BAHIAS,
       SUM(CASE WHEN ESTADO_ACTUAL = 'DISPONIBLE' THEN 1 ELSE 0 END) AS DISPONIBLES,
       SUM(CASE WHEN ESTADO_ACTUAL = 'RESERVADA' THEN 1 ELSE 0 END) AS RESERVADAS,
       SUM(CASE WHEN ESTADO_ACTUAL = 'OCUPADA' THEN 1 ELSE 0 END) AS OCUPADAS,
       SUM(CASE WHEN ESTADO_ACTUAL = 'FUERA_DE_SERVICIO' THEN 1 ELSE 0 END) AS FUERA_DE_SERVICIO,
       ROUND(100 * SUM(CASE WHEN ESTADO_ACTUAL IN ('RESERVADA', 'OCUPADA') THEN 1 ELSE 0 END) / COUNT(*), 1) AS PORCENTAJE_EN_USO
  FROM V_DIM_BAHIA
 GROUP BY UBICACION
 ORDER BY UBICACION;

-- 2. HORAS PUNTA
--    Cuantos usos comienzan en cada hora del dia (hora de Chile)
SELECT HORA_INICIO,
       COUNT(*) AS USOS
  FROM V_HECHO_USO
 GROUP BY HORA_INICIO
 ORDER BY USOS DESC, HORA_INICIO;

-- 3. PERMANENCIA POR UBICACION Y TIPO DE VEHICULO
--    Con los datos de prueba recien cargados hay tres usos finalizados: 290, 590 y 410 minutos
SELECT b.UBICACION,
       v.TIPO_VEHICULO,
       COUNT(*) AS USOS_FINALIZADOS,
       ROUND(AVG(u.MINUTOS_USO)) AS MINUTOS_PROMEDIO,
       MAX(u.MINUTOS_USO) AS MINUTOS_MAXIMO
  FROM V_HECHO_USO u
  JOIN V_DIM_BAHIA b ON b.ID_BAHIA = u.ID_BAHIA
  JOIN V_DIM_VEHICULO v ON v.ID_VEHICULO = u.ID_VEHICULO
 WHERE u.ESTADO_TRANSACCION = 'FINALIZADA'
 GROUP BY b.UBICACION, v.TIPO_VEHICULO
 ORDER BY b.UBICACION, v.TIPO_VEHICULO;

-- 4. RESULTADO DE LAS RESERVAS
--    Cuantas se concretan, expiran o se cancelan, y cuanto tarda el usuario en llegar.
--    Es el dato para decidir cuanto ampliar la ventana de reserva.
SELECT ESTADO_RESERVA,
       COUNT(*) AS RESERVAS,
       ROUND(100 * COUNT(*) / SUM(COUNT(*)) OVER (), 1) AS PORCENTAJE,
       ROUND(AVG(MINUTOS_VENTANA)) AS MINUTOS_VENTANA,
       ROUND(AVG(MINUTOS_HASTA_CHECKIN), 1) AS MINUTOS_PROMEDIO_HASTA_CHECKIN,
       MAX(MINUTOS_HASTA_CHECKIN) AS MINUTOS_MAXIMO_HASTA_CHECKIN
  FROM V_HECHO_RESERVA
 GROUP BY ESTADO_RESERVA
 ORDER BY RESERVAS DESC;

-- 5. MANTENCION POR BAHIA
--    Tickets totales, cuantos siguen abiertos y horas promedio de resolucion
SELECT b.CODIGO_IOT,
       b.UBICACION,
       COUNT(*) AS TICKETS,
       SUM(CASE WHEN k.ESTADO_TICKET IN ('ABIERTO', 'EN_REVISION') THEN 1 ELSE 0 END) AS ABIERTOS,
       ROUND(AVG(k.HORAS_RESOLUCION), 1) AS HORAS_PROMEDIO_RESOLUCION
  FROM V_HECHO_TICKET k
  JOIN V_DIM_BAHIA b ON b.ID_BAHIA = k.ID_BAHIA
 GROUP BY b.CODIGO_IOT, b.UBICACION
 ORDER BY TICKETS DESC, b.CODIGO_IOT;

-- 6. USO POR ROL
--    Distingue a los funcionarios (COLABORADOR) de los usuarios finales
SELECT us.ROL,
       COUNT(*) AS USOS,
       COUNT(DISTINCT u.ID_USUARIO) AS USUARIOS_DISTINTOS
  FROM V_HECHO_USO u
  JOIN V_DIM_USUARIO us ON us.ID_USUARIO = u.ID_USUARIO
 GROUP BY us.ROL
 ORDER BY USOS DESC;

-- 7. USOS POR DIA
--    Cruza los usos con el calendario para ver la tendencia y el dia de la semana
SELECT f.FECHA,
       f.NOMBRE_DIA,
       COUNT(*) AS USOS,
       SUM(u.MINUTOS_USO) AS MINUTOS_TOTALES
  FROM V_HECHO_USO u
  JOIN V_DIM_FECHA f ON f.FECHA = u.FECHA
 GROUP BY f.FECHA, f.NOMBRE_DIA
 ORDER BY f.FECHA;

-- 8. BATERIA DE LOS DISPOSITIVOS
--    Ultima lectura de bateria de cada bahia; ayuda a anticipar fallas
SELECT b.CODIGO_IOT,
       b.UBICACION,
       b.ESTADO_CONEXION,
       MIN(e.BATERIA) KEEP (DENSE_RANK LAST ORDER BY e.EVENTO_LOCAL) AS ULTIMA_BATERIA,
       MAX(e.EVENTO_LOCAL) AS ULTIMO_EVENTO
  FROM V_HECHO_EVENTO_IOT e
  JOIN V_DIM_BAHIA b ON b.ID_BAHIA = e.ID_BAHIA
 GROUP BY b.CODIGO_IOT, b.UBICACION, b.ESTADO_CONEXION
 ORDER BY ULTIMA_BATERIA;
